### ISSUE TITLE
Payment channels

### ISSUE THREAD

**Issue by YVyshnevskyi** [ZhOEC/Erc.Households.Backend#2]
create model PaymentChannel
Id int,
Name string,
RecordpointFieldName string,
SumFieldName string,
DateFieldName string,
TextDateFormat string,
PersonFieldName string,
TotalRecord int
Type int

implement CRUD operations in database

create UI for PaymentChanchannel (list, add, edit, delete)

**Comment by hordii-ztoe** [comment]
branches:
[backend:payment-channel](https://github.com/ZhOEC/Erc.Households.Server/tree/payment-channel)
[ui:payment-channel](https://github.com/ZhOEC/Erc.Households.UI/tree/payment-channel)

**Comment by hordii-ztoe** [comment]
Done in [052a38f](https://github.com/ZhOEC/Erc.Households.Server/commit/052a38f3b361abec73419df9fe32195014acadfa)
